// Generated by gencpp from file mode_manager/ModeRequestResponse.msg
// DO NOT EDIT!


#ifndef MODE_MANAGER_MESSAGE_MODEREQUESTRESPONSE_H
#define MODE_MANAGER_MESSAGE_MODEREQUESTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mode_manager
{
template <class ContainerAllocator>
struct ModeRequestResponse_
{
  typedef ModeRequestResponse_<ContainerAllocator> Type;

  ModeRequestResponse_()
    : response_data()  {
    }
  ModeRequestResponse_(const ContainerAllocator& _alloc)
    : response_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _response_data_type;
  _response_data_type response_data;





  typedef boost::shared_ptr< ::mode_manager::ModeRequestResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mode_manager::ModeRequestResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ModeRequestResponse_

typedef ::mode_manager::ModeRequestResponse_<std::allocator<void> > ModeRequestResponse;

typedef boost::shared_ptr< ::mode_manager::ModeRequestResponse > ModeRequestResponsePtr;
typedef boost::shared_ptr< ::mode_manager::ModeRequestResponse const> ModeRequestResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mode_manager::ModeRequestResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mode_manager::ModeRequestResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mode_manager::ModeRequestResponse_<ContainerAllocator1> & lhs, const ::mode_manager::ModeRequestResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response_data == rhs.response_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mode_manager::ModeRequestResponse_<ContainerAllocator1> & lhs, const ::mode_manager::ModeRequestResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mode_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mode_manager::ModeRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mode_manager::ModeRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mode_manager::ModeRequestResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mode_manager::ModeRequestResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mode_manager::ModeRequestResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mode_manager::ModeRequestResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mode_manager::ModeRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8decf635d15fee3900d3c2f56dbbbeeb";
  }

  static const char* value(const ::mode_manager::ModeRequestResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8decf635d15fee39ULL;
  static const uint64_t static_value2 = 0x00d3c2f56dbbbeebULL;
};

template<class ContainerAllocator>
struct DataType< ::mode_manager::ModeRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mode_manager/ModeRequestResponse";
  }

  static const char* value(const ::mode_manager::ModeRequestResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mode_manager::ModeRequestResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response_data\n"
;
  }

  static const char* value(const ::mode_manager::ModeRequestResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mode_manager::ModeRequestResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeRequestResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mode_manager::ModeRequestResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mode_manager::ModeRequestResponse_<ContainerAllocator>& v)
  {
    s << indent << "response_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.response_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODE_MANAGER_MESSAGE_MODEREQUESTRESPONSE_H
