// Generated by gencpp from file mode_manager/ModeRequestRequest.msg
// DO NOT EDIT!


#ifndef MODE_MANAGER_MESSAGE_MODEREQUESTREQUEST_H
#define MODE_MANAGER_MESSAGE_MODEREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mode_manager
{
template <class ContainerAllocator>
struct ModeRequestRequest_
{
  typedef ModeRequestRequest_<ContainerAllocator> Type;

  ModeRequestRequest_()
    : request_data()  {
    }
  ModeRequestRequest_(const ContainerAllocator& _alloc)
    : request_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _request_data_type;
  _request_data_type request_data;





  typedef boost::shared_ptr< ::mode_manager::ModeRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mode_manager::ModeRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ModeRequestRequest_

typedef ::mode_manager::ModeRequestRequest_<std::allocator<void> > ModeRequestRequest;

typedef boost::shared_ptr< ::mode_manager::ModeRequestRequest > ModeRequestRequestPtr;
typedef boost::shared_ptr< ::mode_manager::ModeRequestRequest const> ModeRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mode_manager::ModeRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mode_manager::ModeRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mode_manager::ModeRequestRequest_<ContainerAllocator1> & lhs, const ::mode_manager::ModeRequestRequest_<ContainerAllocator2> & rhs)
{
  return lhs.request_data == rhs.request_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mode_manager::ModeRequestRequest_<ContainerAllocator1> & lhs, const ::mode_manager::ModeRequestRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mode_manager

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mode_manager::ModeRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mode_manager::ModeRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mode_manager::ModeRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mode_manager::ModeRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mode_manager::ModeRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mode_manager::ModeRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mode_manager::ModeRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d0e41720c8d7bc6e697895f7a38cf0c";
  }

  static const char* value(const ::mode_manager::ModeRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d0e41720c8d7bc6ULL;
  static const uint64_t static_value2 = 0xe697895f7a38cf0cULL;
};

template<class ContainerAllocator>
struct DataType< ::mode_manager::ModeRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mode_manager/ModeRequestRequest";
  }

  static const char* value(const ::mode_manager::ModeRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mode_manager::ModeRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string request_data\n"
;
  }

  static const char* value(const ::mode_manager::ModeRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mode_manager::ModeRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.request_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mode_manager::ModeRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mode_manager::ModeRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "request_data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.request_data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MODE_MANAGER_MESSAGE_MODEREQUESTREQUEST_H
