// Generated by gencpp from file mode_manager/ModeRequest.msg
// DO NOT EDIT!


#ifndef MODE_MANAGER_MESSAGE_MODEREQUEST_H
#define MODE_MANAGER_MESSAGE_MODEREQUEST_H

#include <ros/service_traits.h>


#include <mode_manager/ModeRequestRequest.h>
#include <mode_manager/ModeRequestResponse.h>


namespace mode_manager
{

struct ModeRequest
{

typedef ModeRequestRequest Request;
typedef ModeRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModeRequest
} // namespace mode_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mode_manager::ModeRequest > {
  static const char* value()
  {
    return "0c900dd8a9e0a09ef71b5a7480dbc006";
  }

  static const char* value(const ::mode_manager::ModeRequest&) { return value(); }
};

template<>
struct DataType< ::mode_manager::ModeRequest > {
  static const char* value()
  {
    return "mode_manager/ModeRequest";
  }

  static const char* value(const ::mode_manager::ModeRequest&) { return value(); }
};


// service_traits::MD5Sum< ::mode_manager::ModeRequestRequest> should match
// service_traits::MD5Sum< ::mode_manager::ModeRequest >
template<>
struct MD5Sum< ::mode_manager::ModeRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mode_manager::ModeRequest >::value();
  }
  static const char* value(const ::mode_manager::ModeRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mode_manager::ModeRequestRequest> should match
// service_traits::DataType< ::mode_manager::ModeRequest >
template<>
struct DataType< ::mode_manager::ModeRequestRequest>
{
  static const char* value()
  {
    return DataType< ::mode_manager::ModeRequest >::value();
  }
  static const char* value(const ::mode_manager::ModeRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mode_manager::ModeRequestResponse> should match
// service_traits::MD5Sum< ::mode_manager::ModeRequest >
template<>
struct MD5Sum< ::mode_manager::ModeRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mode_manager::ModeRequest >::value();
  }
  static const char* value(const ::mode_manager::ModeRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mode_manager::ModeRequestResponse> should match
// service_traits::DataType< ::mode_manager::ModeRequest >
template<>
struct DataType< ::mode_manager::ModeRequestResponse>
{
  static const char* value()
  {
    return DataType< ::mode_manager::ModeRequest >::value();
  }
  static const char* value(const ::mode_manager::ModeRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MODE_MANAGER_MESSAGE_MODEREQUEST_H
